#!/usr/bin/env bash
# AVIONIX — First-time setup script
# Run: chmod +x setup.sh && ./setup.sh

set -e

BLUE='\033[0;34m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'

echo -e "${BLUE}"
cat << 'LOGO'
    _  _   ___  ___  _  _  ___  _  _
   /_\| | | __|/ _ \| \| ||_ _|| \/ |
  / _ \ |_| _|| (_) | .` | | |  >  <
 /_/ \_\____|___|\___/|_|\_||___||_/\_|
LOGO
echo -e "${NC}"
echo -e "${BLUE}AVIONIX ATC — First-time Setup${NC}"
echo "================================================"

# Check dependencies
echo -e "\n${YELLOW}Checking dependencies...${NC}"
command -v docker >/dev/null 2>&1 || { echo -e "${RED}✗ Docker not found. Install from https://docs.docker.com/get-docker/${NC}"; exit 1; }
command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1 || { echo -e "${RED}✗ Docker Compose v2 not found${NC}"; exit 1; }
echo -e "${GREEN}✓ Docker $(docker --version | cut -d' ' -f3 | tr -d ',')${NC}"
echo -e "${GREEN}✓ Docker Compose $(docker compose version --short)${NC}"

# Check memory
TOTAL_MEM=$(free -g | awk '/^Mem:/{print $2}' 2>/dev/null || sysctl -n hw.memsize | awk '{print int($0/1073741824)}' 2>/dev/null || echo "?")
echo -e "${GREEN}✓ RAM: ${TOTAL_MEM}GB detected${NC}"
if [ "$TOTAL_MEM" != "?" ] && [ "$TOTAL_MEM" -lt 7 ]; then
  echo -e "${YELLOW}⚠ Warning: 8GB RAM minimum recommended (detected ${TOTAL_MEM}GB)${NC}"
fi

# Create .env if not exists
if [ -f .env ]; then
  echo -e "\n${YELLOW}.env already exists. Skipping generation.${NC}"
else
  echo -e "\n${YELLOW}Generating .env with random passwords...${NC}"
  gen_pass() { tr -dc 'A-Za-z0-9!@#%^&*' < /dev/urandom | head -c 24; }

  DB_PASS=$(gen_pass)
  KC_DB_PASS=$(gen_pass)
  KC_ADMIN_PASS=$(gen_pass)
  REDIS_PASS=$(gen_pass)
  GRAFANA_PASS=$(gen_pass)

  cat > .env << ENVEOF
# Generated by setup.sh — $(date)
# ─── DATABASE ─────────────────────────────────────────────────────────────────
DB_HOST=postgres
DB_PORT=5432
DB_NAME=avionix
DB_USER=avionix
DB_PASSWORD=${DB_PASS}
DB_POOL_MAX=20
DB_SSL=false

# ─── KEYCLOAK ─────────────────────────────────────────────────────────────────
KEYCLOAK_URL=http://keycloak:8080
KEYCLOAK_REALM=avionix
KEYCLOAK_CLIENT_ID=avionix-services
KEYCLOAK_CLIENT_SECRET=avionix-svc-secret-$(gen_pass)
KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=${KC_ADMIN_PASS}
KC_HOSTNAME=localhost
KC_DB_PASSWORD=${KC_DB_PASS}

# ─── REDIS ────────────────────────────────────────────────────────────────────
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=${REDIS_PASS}

# ─── KAFKA ────────────────────────────────────────────────────────────────────
KAFKA_BROKERS=kafka:29092

# ─── MONITORING ───────────────────────────────────────────────────────────────
GRAFANA_PASSWORD=${GRAFANA_PASS}

# ─── APP ──────────────────────────────────────────────────────────────────────
NODE_ENV=production
LOG_LEVEL=info

# ─── SIMULATOR (optional) ─────────────────────────────────────────────────────
SIM_FLIGHT_COUNT=20
SIM_POSITION_INTERVAL_MS=4000
SIM_AUTO_START=false
ENVEOF

  echo -e "${GREEN}✓ .env created${NC}"
  echo ""
  echo -e "${YELLOW}╔══════════════════════════════════════════════════╗${NC}"
  echo -e "${YELLOW}║  SAVE THESE CREDENTIALS — shown only once        ║${NC}"
  echo -e "${YELLOW}╠══════════════════════════════════════════════════╣${NC}"
  echo -e "${YELLOW}║  Keycloak Admin:  admin / ${KC_ADMIN_PASS}    ║${NC}"
  echo -e "${YELLOW}║  Grafana:         admin / ${GRAFANA_PASS}    ║${NC}"
  echo -e "${YELLOW}╚══════════════════════════════════════════════════╝${NC}"
fi

echo ""
echo -e "${GREEN}Setup complete! Run the next step:${NC}"
echo -e "${BLUE}  ./deploy.sh${NC}"
echo ""
